HaverProject/Controllers/NCRController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HaverProject.Data;
using HaverProject.Models;
using System.Linq.Expressions;
using Microsoft.Data.SqlClient;
using CateringManagement.Utilities;
using static System.Runtime.InteropServices.JavaScript.JSType;
using HaverProject.Utilities;
using HaverProject.ViewModel;
using NuGet.Protocol.Plugins;
using Microsoft.AspNetCore.Authorization;
using Rotativa.AspNetCore; 

namespace HaverProject.Controllers
{
    public class NCRController : ElephantController
    {
        private readonly HaverContext _context;
        private readonly IMyEmailSender _emailSender;

        public NCRController(HaverContext context, IMyEmailSender emailSender)
        {
            _context = context;
            _emailSender = emailSender;
        }
        public async Task<IActionResult> Dashboard()
        {


            DateTime fiveYearsAgo = DateTime.Today.AddYears(-5);

            // Query records older than five years
            var records = _context.Ncrs
                .Where(x => x.Date < fiveYearsAgo)
                .ToList();
            foreach (var record in records)
            {
                // Assuming you want to update a field named 'FieldToUpdate'
                record.Status = "Archieve";

                // Mark the entity as modified (if necessary)
                _context.Entry(record).State = EntityState.Modified;
            }

            // Save changes to the database
            _context.SaveChanges();
      

            var ncrLogsQuerya = (from e in _context.Ncrs
                                 where e.Status != "Closed"
                                 where e.Status != "Archieve"
                                 where e.Status != "Void"
                                 select e
                                  );
            ViewData["AllNcrCount"] = (string)ncrLogsQuerya.Count().ToString();
            var ncrLogsQuery = (from e in _context.Ncrs
                                where e.Status == "Engineering"
                                select e
                                      );
            ViewData["EngineeringNcrCount"] = (string)ncrLogsQuery.Count().ToString();
            var ncrLogsQueryp = (from e in _context.Ncrs
                                where e.Status == "Purchase"
                                select e
                                );
            ViewData["PurchaseNcrCount"] = (string)ncrLogsQueryp.Count().ToString();
            var ncrLogsQueryc = (from e in _context.Ncrs
                                 where e.Status == "Closed"
                                 select e
                             );
            ViewData["ClosedNcrCount"] = (string)ncrLogsQueryc.Count().ToString();
            var ncrLogsQueryr = (from e in _context.Ncrs
                                 where e.Status == "Review"
                                 select e
                           );
            ViewData["ReviewNcrCount"] = (string)ncrLogsQueryr.Count().ToString();
            var ncrLogsQueryar = (from e in _context.Ncrs
                                 where e.Status == "Archieve"
                                 select e
                         );
            ViewData["ArchievedNcrCount"] = (string)ncrLogsQueryar.Count().ToString();
            var ncrLogsQueryv = (from e in _context.Ncrs
                                  where e.Status == "Void"
                                  select e
                        );
            ViewData["VoidNcrCount"] = (string)ncrLogsQueryv.Count().ToString();


            return View("Dashboard");
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Archieve(int? id)
        {
            if (id == null || _context.Ncrs == null)
            {
                return NotFound();
            }

            var nCR = await _context.Ncrs
                 .Include(p => p.NCRPhotos)
                 .Include(n => n.Supplier)
                 .FirstOrDefaultAsync(m => m.ID == id);
            if (nCR == null)
            {
                return NotFound();
            }
            nCR.Status = "Archieve";
            _context.Attach(nCR).State = EntityState.Modified;
            await _context.SaveChangesAsync();
            Dashboard();
            
            return View("Dashboard");
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Void(int? id, string reason, string VoidReason)
        {
            var nCR = await _context.Ncrs.FindAsync(id);

            if (nCR == null)
            {
                return NotFound();
            }

            // Set the status to "Void"
            nCR.Status = "Void";

            // Set the void reason
            nCR.VoidReason = VoidReason;
            _context.Entry(nCR).State = EntityState.Modified;
            try
            {
                // Save changes to mark the NCR as void
                await _context.SaveChangesAsync();

                // If a void comment is provided, add it to the NCR's comments
                if (!string.IsNullOrEmpty(VoidReason))
                {
                    var newComment = new NCRComment
                    {
                        NCRId = nCR.ID,
                        CommentText = VoidReason,
                        CreatedAt = DateTime.Now
                    };

                    // Add the comment to the NCR's comment list
                    if (nCR.Comments == null)
                    {
                        nCR.Comments = new List<NCRComment>();
                    }
                    nCR.Comments.Add(newComment);

                    // Save changes to the database again to include the comment
                    await _context.SaveChangesAsync();
                }

                ViewData["VoidMessage"] = "NCR voided successfully."; // Set success message
            }
            catch (DbUpdateException ex)
            {
                // Handle potential database errors gracefully (e.g., logging, error messages)
                return View("Error"); // Or redirect to an error page
            }

            return RedirectToAction("Index"); // Redirect back to the Index action
        }

        [Authorize]
        public async Task<IActionResult> VoidNcr(string searchString, int? id, string answer, DateTime? date, long? poNumber, string status, int supplier, int? page, int pageSizeID, string actionButton, string sortOrder, string sortDirection = "asc", string sortField = "NCRNumber")
        {
            if (page == null)
            {
                page = 1;
            }

            var ncrLogsQuery = (from e in _context.Ncrs
                                where e.Status == "Void"
                                select e
                            )
                            .Include(f => f.Supplier)
                            .AsNoTracking();

            ViewData["EngineeringNcrCount"] = (string)ncrLogsQuery.Count().ToString();
            ViewData["NCRNumberSortParam"] = string.IsNullOrEmpty(sortOrder) ? "ncr_number_desc" : "";
            ViewData["DateSortParam"] = sortOrder == "Date" ? "date_desc" : "Date";
            ViewData["PONumberSortParm"] = string.IsNullOrEmpty(sortOrder) ? "ponumber_desc" : "";
            ViewData["SupplierSortParm"] = sortOrder == "Supplier" ? "supplier_desc" : "Supplier";
            ViewData["StatusSortParam"] = sortOrder == "Status" ? "status_desc" : "Status";


            // Apply filters based on user input
            if (!string.IsNullOrEmpty(searchString))
            {
                ncrLogsQuery = ncrLogsQuery.Where(n => n.NCRNumber.Contains(searchString)

                                             || n.DescriptionItemID.Contains(searchString));
            }

            if (id != null)
            {
                ncrLogsQuery = ncrLogsQuery.Where(n => n.ID == id);
            }

            if (poNumber != null)
            {
                ncrLogsQuery = ncrLogsQuery.Where(n => n.PONumber == poNumber);
            }

            if (!string.IsNullOrEmpty(status))
            {
                ncrLogsQuery = ncrLogsQuery.Where(n => n.Status == status);
            }

            if (date != null)
            {
                // Filter from the start of the provided date to the end of the day
                DateTime startDate = date.Value.Date;
                DateTime endDate = startDate.AddDays(1);
                ncrLogsQuery = ncrLogsQuery.Where(n => n.Date >= startDate && n.Date < endDate);
            }

            // Apply sorting based on the selected sortField and sortDirection
            switch (sortField)
            {
                case "NCRNumber":
                    ncrLogsQuery = sortDirection == "desc" ? ncrLogsQuery.OrderByDescending(n => n.NCRNumber) : ncrLogsQuery.OrderBy(n => n.NCRNumber);
                    break;
                case "Date":
                    ncrLogsQuery = sortDirection == "desc" ? ncrLogsQuery.OrderByDescending(n => n.Date) : ncrLogsQuery.OrderBy(n => n.Date);
                    break;
                case "PONumber":
                    ncrLogsQuery = sortDirection == "desc" ? ncrLogsQuery.OrderByDescending(n => n.PONumber) : ncrLogsQuery.OrderBy(n => n.PONumber);
                    break;
                case "Supplier":
                    ncrLogsQuery = sortDirection == "desc" ? ncrLogsQuery.OrderByDescending(n => n.Supplier.Name) : ncrLogsQuery.OrderBy(n => n.Supplier.Name);
                    break;
                case "Status":
                    ncrLogsQuery = sortDirection == "desc" ? ncrLogsQuery.OrderByDescending(n => n.Status) : ncrLogsQuery.OrderBy(n => n.Status);
                    break;

                default:
                    ncrLogsQuery = ncrLogsQuery.OrderBy(n => n.PONumber);

HaverProject/Controllers/SapController.cs
using HaverProject.Data;
using HaverProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HaverProject.Controllers
{
    public class SapController : Controller
    {
        private readonly HaverContext _context;

        public SapController(HaverContext context)
        {
            _context = context;
        }

        // GET: Sap
        public async Task<IActionResult> Index()
        {
            return View(await _context.SapNos.ToListAsync());
        }
        // GET: Sap/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.SapNos == null)
            {
                return NotFound();
            }

            var sap = await _context.SapNos
                .FirstOrDefaultAsync(m => m.Name == id);
            if (sap == null)
            {
                return NotFound();
            }

            return View(sap);
        }
        // GET: Sap/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ItemProblems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] SapNo sap)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sap);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(sap);
        }
        // GET: Sap/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.SapNos == null)
            {
                return NotFound();
            }

            var sap = await _context.SapNos.FindAsync(id);
            if (sap == null)
            {
                return NotFound();
            }
            return View(sap);
        }

        // POST: Sap/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Name")] SapNo sap)
        {
            if (id != sap.Name)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sap);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SapExists(sap.Name))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sap);
        }

        // GET: Sap/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null || _context.SapNos == null)
            {
                return NotFound();
            }

            var sap = await _context.SapNos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sap == null)
            {
                return NotFound();
            }

            return View(sap);
        }

        // POST: Sap/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.SapNos == null)
            {
                return Problem("Entity set 'HaverContext.Sap'  is null.");
            }
            var sap = await _context.SapNos.FindAsync(id);
            if (sap != null)
            {
                _context.SapNos.Remove(sap);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SapExists(string id)
        {
            return _context.SapNos.Any(e => e.Name == id);
        }

    }
}

HaverProject/Views/Shared/Dashboard.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Dashboard</title>
    <style>
        .grid-container {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            grid-template-rows: repeat(3, auto);
        }

        .grid-item {
            border: none;
            padding: 20px;
            text-align: center;
        }

            .grid-item:nth-child(1) {
                grid-row: span 3;
                grid-column: 1;
            }
    </style>
</head>

<body>
    <h1 style="text-align:center">Dashboard</h1>
    <div class="container">
        <div class="mb-2">
            @if (User.Identity.IsAuthenticated)
            {
                @if (User.IsInRole("Admin") || User.IsInRole("QualityInspector"))
                {
                    <a asp-action="Create" asp-controller="NCR" class="btn btn-sm btn-outline-success"
                       role="button" data-bs-toggle="tooltip">
                        <strong>Create New NCR</strong>
                    </a>
                }
            }
        </div>
        <div class="grid-container">
            <div class="grid-item">
                <a href="@Url.Action("Index", "NCR")" class="text-decoration-none text-dark">
                    <div class="p-3 mb-3 bg-light border shadow-sm d-flex justify-content-around align-items-center rounded h-100">
                        <div>
                            <h3 class="fs-2" asp-controller="NCR">@ViewData["AllNcrCount"]</h3>
                            <p class="fs-5">All NCRs</p>
                        </div>
                        <i class="fa-solid fa-list-ol fa-3x"></i>
                    </div>
                </a>
            </div>
            <div class="grid-item">
                <a href="@Url.Action("EngineeringNcr", "NCR")" class="text-decoration-none text-dark">
                    <div class="p-3 mb-3 bg-light border shadow-sm d-flex justify-content-around align-items-center rounded">
                        <div>
                            <h3 class="fs-2" asp-controller="NCR">@ViewData["EngineeringNcrCount"]</h3>
                            <p class="fs-5">NCRs</p>
                            <figcaption class="blockquote-footer">Engineering Stage</figcaption>
                        </div>
                        <i class="fa-solid fa-gears fa-3x"></i>
                    </div>
                </a>
            </div>
            <div class="grid-item">
                <a href="@Url.Action("PurchaseNcr", "NCR")" class="text-decoration-none text-dark">
                    <div class="p-3 mb-3 bg-light border shadow-sm d-flex justify-content-around align-items-center rounded">
                        <div>
                            <h3 class="fs-2" asp-controller="NCR">@ViewData["PurchaseNcrCount"]</h3>
                            <p class="fs-5">NCRs</p>
                            <figcaption class="blockquote-footer">Purchase Stage</figcaption>
                        </div>
                        <i class="fa-solid fa-circle-check fa-3x"></i>
                    </div>
                </a>
            </div>
            <div class="grid-item">
                <a href="@Url.Action("ReviewNcr", "NCR")" class="text-decoration-none text-dark">
                    <div class="p-3 mb-3 bg-light border shadow-sm d-flex justify-content-around align-items-center rounded">
                        <div>
                            <h3 class="fs-2" asp-controller="NCR">@ViewData["ReviewNcrCount"]</h3>
                            <p class="fs-5">NCRs</p>
                            <figcaption class="blockquote-footer">Review Stage</figcaption>
                        </div>
                        <i class="fa-solid fa-user-check fa-3x"></i>
                    </div>
                </a>
            </div>
            <div class="grid-item">
                <a href="@Url.Action("ClosedNcr", "NCR")" class="text-decoration-none text-dark">
                    <div class="p-3 mb-3 bg-light border shadow-sm d-flex justify-content-around align-items-center rounded">
                        <div>
                            <h3 class="fs-2" asp-controller="NCR">@ViewData["ClosedNcrCount"]</h3>
                            <p class="fs-5">NCRs</p>
                            <figcaption class="blockquote-footer">Closed Stage</figcaption>
                        </div>
                        <i class="fa-solid fa-lock fa-3x"></i>
                    </div>
                </a>
            </div>
            <div class="grid-item">
                <a href="@Url.Action("ArchievedNcr", "NCR")" class="text-decoration-none text-dark">
                    <div class="p-3 mb-3 bg-light border shadow-sm d-flex justify-content-around align-items-center rounded">
                        <div>
                            <h3 class="fs-2" asp-controller="NCR">@ViewData["ArchievedNcrCount"]</h3>
                            <p class="fs-5">Archived NCRs</p>
                        </div>
                        <i class="fa-regular fa-folder-closed fa-3x"></i>
                    </div>
                </a>
            </div>
            <div class="grid-item">
                <a href="@Url.Action("VoidNcr", "NCR")" class="text-decoration-none text-dark">
                    <div class="p-3 mb-3 bg-light border shadow-sm d-flex justify-content-around align-items-center rounded">
                        <div>
                            <h3 class="fs-2" asp-controller="NCR">@ViewData["VoidNcrCount"]</h3>
                            <p class="fs-5">Void NCRs</p>
                        </div>
                        <i class="fa-regular fa-circle-xmark fa-3x"></i>
                    </div>
                </a>
            </div>
        </div>
    </div>
</body>
</html>

HaverProject/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HaverProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HaverProject.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
</head>
<style>
    .navbar-brand {
        height: 120px;
    }

    .container-fluid {
        display: block;
        background-color: #0C2340;
    }

    .navbar-brand img {
        width: 250px;
        height: 110px
    }

    .form-group {
        margin-bottom: 15px;
    }

    h3 {
        text-align: center;
    }
</style>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area=""><img src="~/images/Logo_Main.png" /></a>
                @*  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>*@
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="NCR" asp-action="Dashboard">Dashboard</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="NCR" asp-action="Index">NCR</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="EmailAddress" asp-action="Index">Email</a>
                            </li>

                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="UserRole" asp-action="Index">Manage User Role</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link text-light dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Admin Tools
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" asp-area="" asp-controller="Suppliers" asp-action="Index">Supplier</a></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="ItemProblems" asp-action="Index">Item Problems</a></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="Sap" asp-action="Index">Sap No.</a></li>
                                    </ul>
                                </li>
                            }           }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - HaverProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HaverProject/Views/Shared/_PageSizeModal.cshtml
<!-- Modal-->
<div class="modal fade" id="pageSizeModal" tabindex="-1" role="dialog" aria-labelledby="pageSizeModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="pageSizeModalLabel">Set Page Size</h4>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <div class="form-row">
                    <div class="form-group col-md-12">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Page Size: </span>
                            </div>
                            @Html.DropDownList("pageSizeID", null, htmlAttributes: new { @class = "form-control" })
                            <div class="input-group-append">
                                <input type="submit" class="btn btn-primary" value="Set Page Size" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

HaverProject/Views/Shared/_PagingNavBar.cshtml
<partial name="_PageSizeModal"/>
<nav aria-label="Page navigation">
    @{
        if (Model.TotalPages == 0)
        {
            <ul class="pagination justify-content-center pagination-sm" style="margin:20px 0">
                <li class="page-item active">
                    <button type="button" title="Click to change page size." data-bs-toggle="modal" data-bs-target="#pageSizeModal" class="btn page-link">
                        No Data to Show
                    </button>
                </li>
            </ul>
        }
        else if (Model.TotalPages == 1)
        {
            <ul class="pagination justify-content-center pagination-sm" style="margin:20px 0">
                <li class="page-item active">
                    <button type="button" title="Click to change page size." data-bs-toggle="modal" data-bs-target="#pageSizeModal" class="btn page-link">
                        Page @Model.PageIndex of @Model.TotalPages
                    </button>
                </li>
            </ul>
        }
        else
        {
            var jumpAmount = (Model.TotalPages > 25) ? 10 : 5;
            var prevDisabled = !Model.HasPreviousPage ? "disabled='disabled'" : "";
            var nextDisabled = !Model.HasNextPage ? "disabled='disabled'" : "";
            var stepBack = (Model.PageIndex <= jumpAmount) ? 1 : Model.PageIndex - jumpAmount;
            var stepForward = (Model.PageIndex + jumpAmount > Model.TotalPages) ? Model.TotalPages : Model.PageIndex + jumpAmount;
            <ul class="pagination justify-content-center pagination-sm" style="margin:20px 0">
                <li class="page-item">
                    <button type="submit" name="page" value="1" @prevDisabled class="btn page-link">
                        <span aria-hidden="true">&lArr;</span>&nbsp;First
                    </button>
                </li>
                <li class="page-item d-none d-md-inline">
                    <button type="submit" name="page" data-bs-toggle="tooltip" value="@(stepBack)" @prevDisabled
                            title="Jump Back @(Model.PageIndex - stepBack) Pages" class="btn page-link">
                        <span aria-hidden="true">&lArr;</span>
                    </button>
                </li>
                <li class="page-item">
                    <button type="submit" name="page" @prevDisabled value="@(Model.PageIndex - 1)" class="btn page-link">
                        &nbsp;<span aria-hidden="true">&larr;</span>&nbsp;<span class="d-none d-md-inline">Previous</span>
                    </button>
                </li>
                <li class="page-item active">
                    <button type="button" title="Click to change page size." data-bs-toggle="modal" data-bs-target="#pageSizeModal" class="btn page-link">
                        <span class="d-none d-md-inline">Pg. </span>@Model.PageIndex of @Model.TotalPages
                    </button>
                </li>
                <li class="page-item">
                    <button type="submit" name="page" @nextDisabled value="@(Model.PageIndex + 1)" class="btn page-link">
                        <span class="d-none d-md-inline">Next</span>&nbsp;<span aria-hidden="true">&rarr;</span>&nbsp;
                    </button>
                </li>
                <li class="page-item d-none d-md-inline">
                    <button type="submit" data-bs-toggle="tooltip" name="page" @nextDisabled value="@(stepForward)"
                            title="Jump Forward @(stepForward - Model.PageIndex) Pages" class="btn page-link">
                        <span aria-hidden="true">&rArr;</span>
                    </button>
                </li>
                <li class="page-item">
                    <button type="submit" name="page" @nextDisabled value="@(Model.TotalPages)" class="btn page-link">
                        Last&nbsp;<span aria-hidden="true">&rArr;</span>
                    </button>
                </li>
            </ul>
        }
    }
</nav>